# Generated by Django 5.2.9 on 2025-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='guud_97008 같은 크롤링 원본 상품 ID (없으면 비워둠)', max_length=64, null=True, verbose_name='외부 상품 ID')),
                ('category', models.CharField(max_length=64, verbose_name='카테고리')),
                ('brand_name', models.CharField(blank=True, default='', max_length=255, verbose_name='브랜드명')),
                ('product_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('link_url', models.URLField(max_length=1024, verbose_name='상품 링크 URL')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='대표 이미지 URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='상품 설명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격(원)')),
                ('mood_keywords', models.JSONField(blank=True, default=list, help_text='RAG / VLM 에서 추출한 무드 태그 리스트', verbose_name='무드 키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
    ]
